title: ""
author: Colin Jarratt
description: Suicide prevention researcher focused on behavior change and psychological transitions
theme: minima

header_pages:
  - index.md
  - cv.md
  - projects.md

minima:
  skin: auto
  social_links:
    github: colinjarratt15
    twitter: colinjarratt15
    linkedin: colinjarratt

github_username: colinjarratt15
twitter_username: colinjarratt15
linkedin_username: colinjarratt
