title: Colin Jarratt
description: Suicide prevention research focused on behavior change and psychological transitions
remote_theme: jekyll/minima

minima:
  skin: auto
  social_links:
    github: colinjarratt15
    twitter: colinjarratt15
    linkedin: colinjarratt

author: ""

header_pages:
  - index.md
  - cv.md
  - projects.md
